---
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  BastionAMIImage:
    Description: AMI to use for bastion host
    Type: AWS::EC2::Image::Id
    Default: ami-061a2d878e5754b62
  EC2KeyPair:
    Description: EC2 Keypair
    Type: AWS::EC2::KeyPair::KeyName
    Default: aws-eu-keys
  SecurityGroup:
    Description: EC2 Security Group
    Type: AWS::EC2::SecurityGroup::Id
  BastionSubnet:
    Description: Bastion Subnet
    Type: AWS::EC2::Subnet::Id
  InstanceProfile:
    Description: IAM Profile
    Type: String
  CertsS3Bucket:
    Description: Certs S3 Bucket
    Type: String
Resources:
  BastionHost:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref BastionAMIImage
      IamInstanceProfile: !Ref InstanceProfile
      InstanceType: t2.micro
      KeyName: !Ref EC2KeyPair
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: '0'
          DeleteOnTermination: 'true'
          GroupSet: 
            - !Ref SecurityGroup
          SubnetId: !Ref BastionSubnet
      UserData: 
        Fn::Base64:
          Fn::Join:
            - ""
            -
              - "#!/bin/bash -v\n"
              - "# Install AWS cfn tools for ubuntu\n"
              - "apt-get update\n"
              - "apt-get -y install python-setuptools\n"
              - "mkdir aws-cfn-bootstrap-latest\n"
              - "curl https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz | tar xz -C aws-cfn-bootstrap-latest --strip-components 1\n"
              - "easy_install aws-cfn-bootstrap-latest\n"
              - "# Function to return error code to the wait handle\n"
              - "function handle_error\n"
              - "{\n"
              - !Sub " /usr/local/bin/cfn-signal -e 1 --stack ${AWS::StackName} -r 'Failed to run cfn-init' --resource BastionHost --region ${AWS::Region}\n"
              - " exit 1\n"
              - "}\n"
              - !Sub "/usr/local/bin/cfn-init -s ${AWS::StackName} -r BastionHost --region ${AWS::Region} || handle_error 'Failed to run cfn-init'\n"
              - "# Return success\n"
              - !Sub "/usr/local/bin/cfn-signal -e 0 --stack ${AWS::StackName} -r 'Stack complete' --resource BastionHost --region ${AWS::Region}\n"
    CreationPolicy:
      ResourceSignal:
        Timeout: "PT5M"
    Metadata:
      AWS::CloudFormation::Init: 
        config: 
          groups: 
            users: {}
          users: 
            user:
              groups:
                - 'users'
              uid: '501'
              homeDir: "/home/user"
          packages:
            apt:
              awscli: []
          files: 
            "/usr/local/bin/cfssl":
              source: "https://pkg.cfssl.org/R1.2/cfssl_linux-amd64"
              group: root
              owner: user
              mode: "000550"
            "/usr/local/bin/cfssljson":
              source: "https://pkg.cfssl.org/R1.2/cfssljson_linux-amd64"
              group: root
              owner: user
              mode: "000550"
            "/usr/local/bin/kubectl":
              source: "https://storage.googleapis.com/kubernetes-release/release/v1.10.2/bin/linux/amd64/kubectl"
              group: root
              owner: user
              mode: "000550"
            "/certs/ca-config.json":
              mode: "000550"
              group: root
              owner: root			  
              content:
                Fn::Join:
                  - "\n"
                  -
                    - '{'
                    - '  "signing": {'
                    - '    "default": {'
                    - '      "expiry": "8760h"'
                    - '    },'
                    - '   "profiles": {'
                    - '      "kubernetes": {'
                    - '        "usages": ["signing", "key encipherment", "server auth", "client auth"],'
                    - '        "expiry": "8760h"'
                    - '      }'
                    - '    }'
                    - '  }'
                    - '}'
            "/certs/ca-csr.json":
              mode: "000755"
              group: root
              owner: root			  
              content:
                Fn::Join:
                  - "\n"
                  -
                    - '{'
                    - '"CN": "Kubernetes",'
                    - '  "key": {'
                    - '    "algo": "rsa",'
                    - '    "size": 2048'
                    - '  },'
                    - '  "names": ['
                    - '    {'
                    - '      "C": "US",'
                    - '      "L": "Portland",'
                    - '      "O": "Kubernetes",'
                    - '      "OU": "CA",'
                    - '      "ST": "Oregon"'
                    - '    }'
                    - '  ]'
                    - '}'
          commands:
            1testcfssl: 
              command: "cfssl version"
            2testkubectl: 
              command: "kubectl version --client"
            3generateCA: 
              cwd: "/certs"
              command: 'cfssl gencert -initca ca-csr.json | cfssljson -bare ca'
              test: 
                Fn::Join:
                  - ""
                  -
                    - "#!/bin/bash -v\n"
                    - "if [ ! -e 'ca-key.pem' ]; then\n"
                    - "  exit 0\n"
                    - "else\n"
                    - "  exit 1\n"
                    - "fi\n"
            4copyCerts:
              cwd: "/certs"
              command: 
                Fn::Join:
                  - ""
                  -
                    - "aws s3 cp ca-key.pem s3://"
                    - !Ref CertsS3Bucket
                    - " --region "
                    - !Sub "${AWS::Region}"
Outputs:
  BastionHostOut:
    Description: BastionHost created
    Value: !Ref BastionHost
    Export:
      Name: !Sub "${AWS::StackName}-BastionHost"