AWSTemplateFormatVersion: "2010-09-09"
Resources: 
  RootRole: 
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "ec2.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/"
      Policies: 
        - 
          PolicyName: "root"
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - 
                Effect: "Allow"
                Action: "*"
                Resource: "*"
  RootInstanceProfile: 
    Type: "AWS::IAM::InstanceProfile"
    Properties: 
      Path: "/"
      Roles: 
        - 
          Ref: "RootRole"
Outputs:
  RootInstanceProfileOut:
    Description: Root InstanceProfile created
    Value: !Ref RootInstanceProfile
    Export:
      Name: !Sub "${AWS::StackName}-RootInstanceProfile"
  RootRoleOut:
    Description: RootRole created
    Value: !Ref RootRole
    Export:
      Name: !Sub "${AWS::StackName}-RootRole"